### ISSUE TITLE
Allow for no mpi

### ISSUE THREAD

**Issue by fdmalone** [JoonhoLee-Group/ipie#221]
mpi4py chokes on arm, this is no good.

**Comment by fdmalone** [comment]
conda works fyi

**Comment by linusjoonho** [comment]
What does that mean? conda install mpi4py works?

**Comment by fdmalone** [comment]
yeah pip install mpi4py is failing, conda works ok. Would be nice to not rely on MPI more generally

**Comment by linusjoonho** [comment]
@scemama had some ideas for doing direct socket communications. Would you share your ideas with us here?

**Comment by scemama** [comment]
You can check this pdf:
https://zenodo.org/record/5718286/files/parallelism_scemama.pdf

On slide 48, I present interprocess communication and the example used is the computation of pi using a stochastic algorithm. It starts with single-node interprocess communication with pipes, and around slide 60 I present it with sockets. You could use exactly the provided Python examples by replacing pi by the AFQMC energy :-)

My QMC code QMC=Chem doesn't use MPI and uses exactly this design and we scaled up to ~80 000 processes.

I will be happy to help.

**Comment by scemama** [comment]
Also, instead of using sockets, I would recommend using ZeroMQ which is easier and more flexible than sockets. There is a very good Python module pyzmq.

**Comment by scemama** [comment]
I made an example in PR #224

**Comment by fdmalone** [comment]
Closed by #245
