### ISSUE TITLE
[BUG] Number of blocks in example is not correct

### ISSUE THREAD

**Issue by lisayujingwei** [JoonhoLee-Group/ipie#237]
Hello,

I ran this:
https://github.com/linusjoonho/ipie/tree/develop/examples/01-simple

I am using Python 3.8.16 and Linux LSB Version:	:core-4.1-amd64:core-4.1-noarch

Everything is working except for the last step using reblock, where I get this following error:

Traceback (most recent call last):
  File "reblock.py", line 163, in <module>
    main(sys.argv[1:])
  File "reblock.py", line 153, in main
    results = reblock_minimal(
  File "/autofs/nccs-svm1_home1/lisayujingwei/ipie/ipie/analysis/blocking.py", line 364, in reblock_minimal
    rb = reblock_by_autocorr(y, verbose=verbose)
  File "/autofs/nccs-svm1_home1/lisayujingwei/ipie/ipie/analysis/autocorr.py", line 99, in reblock_by_autocorr
    block_size = int(numpy.ceil(tacs[0])) # should take the one with the largest sample size
IndexError: list index out of range

The command I used to run to get the error is
python3 reblock.py -b 10 -f output.dat

This is what my output.dat looks like: (excluding the comments in the beginning and at the end)
...
#
# Available memory on the node is 0.000 GB
            Block                   Weight            WeightFactor            HybridEnergy                  ENumer                  EDenom                  ETotal                  E1Body                  E2Body
                0   6.4000000000000000e+02  6.4000000000000000e+02  0.0000000000000000e+00 -3.3640200271932117e+03  6.4000000000000000e+02 -5.2562812924893940e+00 -1.6806346328075794e+01  1.1550065035586400e+01
                1   6.5497516759547113e+02  6.7231604285669721e+02 -2.3926462032368661e+00 -3.3788287110619849e+03  6.4000000000000011e+02 -5.2794198610343503e+00 -1.6805556761397455e+01  1.1526136900363104e+01
                2   6.4006583279378913e+02  6.4652122015633313e+02 -2.4099678958299324e+00 -3.3897540906834111e+03  6.4000000000000000e+02 -5.2964907666928305e+00 -1.6805781064633802e+01  1.1509290297940971e+01
                3   6.4008923029721768e+02  6.4026125345726746e+02 -2.4277950082790070e+00 -3.3989317333077925e+03  6.4000000000000000e+02 -5.3108308332934264e+00 -1.6805685059959796e+01  1.1494854226666369e+01
                4   6.4007063681477803e+02  6.4018940651184641e+02 -2.4413738898623829e+00 -3.4072874949007546e+03  6.4000000000000000e+02 -5.3238867107824293e+00 -1.6805815100671712e+01  1.1481928389889283e+01
                5   6.4006589572974008e+02  6.4027211328413057e+02 -2.4540684993632613e+00 -3.4132843298162247e+03  6.4000000000000000e+02 -5.3332567653378513e+00 -1.6805756559603807e+01  1.1472499794265955e+01
                6   6.3996586557812623e+02  6.3991614512232889e+02 -2.4498190228675001e+00 -3.4171606814093043e+03  6.3999999999999989e+02 -5.3393135647020387e+00 -1.6805953411863822e+01  1.1466639847161780e+01
                7   6.4010752497295891e+02  6.4018320707679936e+02 -2.4705070020437718e+00 -3.4217525167472049e+03  6.4000000000000000e+02 -5.3464883074175082e+00 -1.6806075950663161e+01  1.1459587643245651e+01
                8   6.3999962693654447e+02  6.4003525900122179e+02 -2.4718508602735625e+00 -3.4253812772348215e+03  6.4000000000000000e+02 -5.3521582456794086e+00 -1.6806323786482899e+01  1.1454165540803487e+01
                9   6.3999990942377519e+02  6.3999254950066324e+02 -2.4773053673661827e+00 -3.4277497711553906e+03  6.4000000000000000e+02 -5.3558590174302978e+00 -1.6807110830427547e+01  1.1451251812997249e+01
               10   6.3999910044875639e+02  6.4000698287637738e+02 -2.4851915473225068e+00 -3.4292934827361264e+03  6.4000000000000000e+02 -5.3582710667751980e+00 -1.6807053034280241e+01  1.1448781967505040e+01
# End Time: Fri Jun 23 12:13:19 2023
# Running time : 27.404914 seconds
...

Thank you for your help!

**Comment by fdmalone** [comment]
Thanks for pointing this out. I think there is some legacy input issue happening here as only 10 blocks are run which is why the block index is out of bounds. The run_tests tool needs to be updated to actually run ipie for the legacy cases and check the steps given in the doc.

**Comment by fdmalone** [comment]
Should be fixed from #245
