### ISSUE TITLE
[BUG] NOCI trial.G not initialized

### ISSUE THREAD

**Issue by AdrianLopez1** [JoonhoLee-Group/ipie#246]
**Describe the bug**
NOCI trial does not initialize one-body Greens function. construct_mean_field_shift in ipie/ipie/propagation/phaseless_base.py requires trial.G .

**To Reproduce**
Run AFQMC with NOCI trial.

**Comment by fdmalone** [comment]
I'm not even sure to what extent NOCI trials are implemented properly. The local energy for example doesn't seem to be implemented?

**Comment by fdmalone** [comment]
I'm implementing these features now
