### ISSUE TITLE
recover the feature of reading in initial_walkers

### ISSUE THREAD

**Issue by jiangtong1000** [JoonhoLee-Group/ipie#252]
https://github.com/JoonhoLee-Group/ipie/blob/b9973b630bd98f55fa59ac3cb78b7a7b928f1306/ipie/qmc/afqmc.py#L157-L167
Hi! It seems ipie removed the feature of using user-defined initial walkers to initialize AFQMC. I understand this is more clean because it can generate walkers based on the type of trial. I was wondering if we can add the flexibility of the `AFQMC` `build` function to allow giving initial walkers by users, since sometimes we may want to restart the calculation from the dumped walkers.

**Comment by fdmalone** [comment]
It would certainly be possible. Just add a default option of None and condition on this. Alternatively the constructor DOES expect walkers as input so you could just build things externally and use the constructor directly, but I think allowing for walkers as input makes sense.
