### ISSUE TITLE
Missing term in the mean field term Hamiltonian

### ISSUE THREAD

**Issue by franappi11** [JoonhoLee-Group/ipie#274]
Hello ipie developers :)
I was looking again at the legacy code for the Hubbard Hamiltonian and I have a doubt: in the function diagonalise mean field, in the file Hubbard_uhf.py, isn't there a missing term? I am referring to the term -0.5 * U * density_up * density_down ( the third term in eq.4 https://arxiv.org/pdf/1107.0976.pdf) 
Thank you for your time and for your excellent work!

**Comment by fdmalone** [comment]
It's been a long time since looking but my guess is that the final term is a global constant (<nu><nd>) so would only serve to shift all the eigenvalues by the same amount so should not effect the convergence.
