### ISSUE TITLE
 The input of dot_real_cplx function A may not be real, could it lead to errors?

### ISSUE THREAD

**Issue by ywlds** [JoonhoLee-Group/ipie#275]
**Describe the bug**
In the local_energy_wicks.py, there are quite a lot of function such as wk.get_ss_doubles and wk.fill_os_doubles and so are dependent on one equation 

@jit(nopython=True, fastmath=True)
// def dot_real_cplx(
//     A,
//     B_real,
//     B_cplx,
// ):
//     """Element wise multiplication of a real number with a complex one.
//     C = A * B
//     Numba complains if types aren't matched so split it up.
//     Parameters
//     ----------
//     A : float
//         Real number / array.
//     B : complex
//         Complex number / array.
//     Returns
//     -------
//     C : complex
//         result
//     """
//     return A * B_real + 1j * (A * B_cplx) //Note this is element-wise operation.

however, I noticed that some input of these function in A is not exactly real during my test, in this case, it would lead some potential errors during the calculation.  
![image](https://github.com/JoonhoLee-Group/ipie/assets/14145559/682ab5cb-522f-4502-84d6-5d06cf353605)

**Comment by fdmalone** [comment]
This looks like it could be a bug, I'm trying to remember why I thought this Lvo tensor should have been real as it's quite a deliberate thing to do. How did you generate the inputs for the above screenshot?

**Comment by ywlds** [comment]
> This looks like it could be a bug, I'm trying to remember why I thought this Lvo tensor should have been real as it's quite a deliberate thing to do. How did you generate the inputs for the above screenshot?

I am testing it with multi-reference trial state with Selected CI and CAS for iron based system.

**Comment by linusjoonho** [comment]
Hi Dingshun - can you give us the script that reproduces this warning?

**Comment by linusjoonho** [comment]
Ah, I actually think the code is working still even though A is complex-valued for numba CPU. Is this problem showing up just for GPU with cupy?

**Comment by fdmalone** [comment]
Yes, I can confirm it works even though it shouldn't if you're just going by the function name and docstring. I was saved by lack of typing (but also this sort of thing would have been caught in a typed language) and by our unit tests which do exercise this code path. Both matrices are complex in general so I will replace this with dot_cplx_cplx.

**Comment by ywlds** [comment]
> Ah, I actually think the code is working still even though A is complex-valued for numba CPU. Is this problem showing up just for GPU with cupy?

Yeah, I use cupy

**Comment by ywlds** [comment]
> Yes, I can confirm it works even though it shouldn't if you're just going by the function name and docstring. I was saved by lack of typing (but also this sort of thing would have been caught in a typed language) and by our unit tests which do exercise this code path. Both matrices are complex in general so I will replace this with dot_cplx_cplx.

Thanks. I will close this comment.
