### ISSUE TITLE
GPU support for MSD trials 

### ISSUE THREAD

**Issue by zohimchandani** [JoonhoLee-Group/ipie#292]
We would like to run large-scale AFQMC calculations using MSD, however, the CPU implementation will create a memory and time bottleneck and hence we need GPU and Multi-GPU support. 

In your original paper, it states that this is work in progress, checking if there are any updates on this please?

Thanks team.

**Comment by fdmalone** [comment]
xref #268

**Comment by linusjoonho** [comment]
Hi Zohim - there are contributors who will merge their codes into ipie by the end of this month.
In essence, we do have GPU and multi-GPU capability for running a large MSD trial now and this will be made publicly available soon.

**Comment by yfhuang93** [comment]
Hi Zohim, Yifei here from Bytedance. We had MSD-AFQMC ready for a single GPU, i.e., with support for wicks calculation, which we'll release by the end of the month, like Joonho said. We plan to extend this to multi-GPU later this year, which feels less technical compared to wicks. 

However, our team at Bytedance does not have a plan for multi-node yet. If there is a high demand for this, we can help out if others would like to weigh in.

**Comment by vvp-nsk** [comment]
Hej!

Just in case, is single GPU support for MSD trial public available yet?

Thank you in advance!

With best regards, 
Victor

**Comment by yfhuang93** [comment]
Hi Victor,

It is submitted as pull request #299. You can check there first. I think it
should be merged very soon. Let me know if you need more information.

Cheers
Yifei

**Comment by davidev886** [comment]
Dear Yifei, following on this I tried the code of the pull request thanks! However, I am not able to run with an MSD trial when I choose a walker UHFWalkersParticleHole and a ParticleHole trial. Is there a simple example I can use? Thanks!

**Comment by davidev886** [comment]
Dear Yifei, this is the error I get

Traceback (most recent call last):
  File "/global/u2/v/vodolad/hybrid_workflow/run_ipie_gpu.py", line 266, in <module>
    afqmc_msd.run()
  File "/global/u2/v/vodolad/ipie_fork/ipie/ipie/qmc/afqmc.py", line 417, in run
    self.setup_estimators(estimator_filename, additional_estimators=additional_estimators)
  File "/global/u2/v/vodolad/ipie_fork/ipie/ipie/qmc/afqmc.py", line 349, in setup_estimators
    self.estimators.compute_estimators(
  File "/global/u2/v/vodolad/ipie_fork/ipie/ipie/estimators/handler.py", line 204, in compute_estimators
    e.compute_estimator(system, walker_batch, hamiltonian, trial)
  File "/global/u2/v/vodolad/ipie_fork/ipie/ipie/estimators/energy.py", line 142, in compute_estimator
    energy = local_energy(system, hamiltonian, walkers, trial)
  File "/global/homes/v/vodolad/.conda/envs/gpu-ipie/lib/python3.10/site-packages/plum/function.py", line 367, in __call__
    method, return_type = self._resolve_method_with_cache(args=args)
  File "/global/homes/v/vodolad/.conda/envs/gpu-ipie/lib/python3.10/site-packages/plum/function.py", line 398, in _resolve_method_with_cache
    method, return_type = self.resolve_method(args)
  File "/global/homes/v/vodolad/.conda/envs/gpu-ipie/lib/python3.10/site-packages/plum/function.py", line 318, in resolve_method
    impl, return_type = self._handle_not_found_lookup_error(e)
  File "/global/homes/v/vodolad/.conda/envs/gpu-ipie/lib/python3.10/site-packages/plum/function.py", line 327, in _handle_not_found_lookup_error
    raise ex from None
  File "/global/homes/v/vodolad/.conda/envs/gpu-ipie/lib/python3.10/site-packages/plum/function.py", line 300, in resolve_method
    method = self._resolver.resolve(target)
  File "/global/homes/v/vodolad/.conda/envs/gpu-ipie/lib/python3.10/site-packages/plum/resolver.py", line 320, in resolve
    raise NotFoundLookupError(self.function_name, target, self.methods)
plum.resolver.NotFoundLookupError: `local_energy(<ipie.systems.generic.Generic object at 0x7fcaa7fc9ba0>,
<ipie.hamiltonians.generic_chunked.GenericRealCholChunked object at
0x7fcaaa052a40>, <ipie.walkers.uhf_walkers.UHFWalkersParticleHole object at
0x7fcaa7fb7e80>, <ipie.trial_wavefunction.particle_hole.ParticleHole object at
0x7fcaaa053970>)` could not be resolved.

Closest candidates are the following:
    local_energy(system: ipie.systems.generic.Generic, hamiltonian:
    typing.Union[ipie.hamiltonians.generic.GenericRealChol,
    ipie.hamiltonians.generic_chunked.GenericRealCholChunked], walkers:
    ipie.walkers.uhf_walkers.UHFWalkers, trial:
    ipie.trial_wavefunction.single_det.SingleDet)
        <function local_energy at 0x7fcaaa42de10> @
    /global/u2/v/vodolad/ipie_fork/ipie/ipie/estimators/energy.py:48
    local_energy(system: ipie.systems.generic.Generic, hamiltonian:
    ipie.hamiltonians.generic.GenericRealChol, walkers:
    ipie.walkers.uhf_walkers.UHFWalkers, trial:
    ipie.trial_wavefunction.particle_hole.ParticleHole)
        <function local_energy at 0x7fcaaa173760> @
    /global/u2/v/vodolad/ipie_fork/ipie/ipie/estimators/energy.py:78
    local_energy(system: ipie.systems.generic.Generic, hamiltonian:
    ipie.hamiltonians.generic.GenericComplexChol, walkers:
    ipie.walkers.uhf_walkers.UHFWalkers, trial:
    ipie.trial_wavefunction.single_det.SingleDet)
        <function local_energy at 0x7fcaaa1725f0> @
    /global/u2/v/vodolad/ipie_fork/ipie/ipie/estimators/energy.py:58

From: yfhuang93 ***@***.***>
Date: Thursday, 25. April 2024 at 11:03
To: JoonhoLee-Group/ipie ***@***.***>
Cc: Davide Vodola ***@***.***>, Comment ***@***.***>
Subject: [EXT] Re: [JoonhoLee-Group/ipie] GPU support for MSD trials (Issue #292)
You don't often get email from ***@***.*** Learn why this is important<https://aka.ms/LearnAboutSenderIdentification>

Hi David, may I ask what kind of error you get first?

**Comment by yfhuang93** [comment]
Hi David, looks like a walker problem with the script you used, which caused the plum error. Simply using the multi-determinant example in ipie should work:

%env CUPY_ACCELERATORS=cutensor # for notebook, for .py you can set this in terminal

import cupy

from ipie.config import config

config.update_option("use_gpu", True)

import h5py
import numpy
from pyscf import fci, gto, mcscf, scf

from ipie.hamiltonians.generic import Generic as HamGeneric
from ipie.qmc.afqmc import AFQMC
from ipie.systems.generic import Generic
from ipie.trial_wavefunction.particle_hole import ParticleHole
from ipie.utils.from_pyscf import gen_ipie_input_from_pyscf_chk

nocca = 4
noccb = 2

mol = gto.M(
    atom=[("N", 0, 0, 0), ("N", (0, 0, 3.0))],
    basis="ccpvdz",
    verbose=3,
    spin=nocca - noccb,
    unit="Bohr",
)
mf = scf.RHF(mol)
mf.chkfile = "scf.chk"
ehf = mf.kernel()
M = 6
N = 6
mc = mcscf.CASSCF(mf, M, N)
mc.chkfile = "scf.chk"
e_tot, e_cas, fcivec, mo, mo_energy = mc.kernel()
coeff, occa, occb = zip(
    *fci.addons.large_ci(fcivec, M, (nocca, noccb), tol=1e-8, return_strs=False)
)
# Need to write wavefunction to checkpoint file.
with h5py.File("scf.chk", "r+") as fh5:
    fh5["mcscf/ci_coeffs"] = coeff
    fh5["mcscf/occs_alpha"] = occa
    fh5["mcscf/occs_beta"] = occb

gen_ipie_input_from_pyscf_chk("scf.chk", mcscf=True)
mol_nelec = [8, 6]

with h5py.File("hamiltonian.h5") as fa:
    chol = fa["LXmn"][()]
    h1e = fa["hcore"][()]
    e0 = fa["e0"][()]

num_basis = chol.shape[1]
system = Generic(nelec=mol_nelec)

num_chol = chol.shape[0]
ham = HamGeneric(
    numpy.array([h1e, h1e]),
    chol.transpose((1, 2, 0)).reshape((num_basis * num_basis, num_chol)),
    e0,
)

# Build trial wavefunction
with h5py.File("wavefunction.h5", "r") as fh5:
    coeff = fh5["ci_coeffs"][:]
    occa = fh5["occ_alpha"][:]
    occb = fh5["occ_beta"][:]
wavefunction = (coeff, occa, occb)
trial = ParticleHole(
    wavefunction,
    mol_nelec,
    num_basis,
    num_dets_for_props=len(wavefunction[0]),
    verbose=True,
)
# trial.compute_trial_energy = True
trial.build()
trial.half_rotate(ham)


afqmc_msd = AFQMC.build(
    mol_nelec,
    ham,
    trial,
    num_walkers=10,
    num_steps_per_block=25,
    num_blocks=10,
    timestep=0.005,
    stabilize_freq=5,
    seed=96264512,
    pop_control_freq=5,
    verbose=True,
)
afqmc_msd.run()
afqmc_msd.finalise(verbose=True)

I didn't change anything besides the GPU option and the ParticleHoleNonChunked to ParticleHole. Let me know if this works for you.

Cheers,
Yifei

**Comment by davidev886** [comment]
it works! thanks :)

**Comment by davidev886** [comment]
sorry again, is there something one should do for having it run on more than one gpus?

**Comment by yfhuang93** [comment]
We don't have multi-GPU support at the moment. It's easy to distribute computation like einsum or wicks to multiple GPUs by splitting the arrays. However, I think a lot of the time the bottleneck is memory. That requires some optimization. I'm planning to spend some time on it later this year.

**Comment by vvp-nsk** [comment]
Hej!

Would it be possible to implement a restart feature from walkers dumped to a disk file?  In this way, one can continue a calculation with MSD trial on a single GPU and approach the desired uncertainty in energy, IMHO. 

With best regards, 
Victor

**Comment by linusjoonho** [comment]
Other feature request such as walker restart should be a separate issue. I am closing this issue.
