### ISSUE TITLE
Building Hamiltonian for some molecules results in an error.

### ISSUE THREAD

**Issue by Koberard** [JoonhoLee-Group/ipie#313]
**Describe the bug**
When running generate_hamiltonian() I get that the modified Cholesky calculation goes out of bounds.

**To Reproduce**
Perform UHF in pyscf. Then build AFQMC.
import numpy as np
from pyscf import gto, scf
from ipie.analysis.autocorr import reblock_by_autocorr
from ipie.config import MPI
# We can extract the qmc data as as a pandas data frame like so
from ipie.analysis.extraction import extract_observable
from ipie.estimators.energy import EnergyEstimator, local_energy_batch
from ipie.qmc.afqmc import AFQMC
from ipie.systems.generic import Generic
from ipie.trial_wavefunction.single_det import SingleDet
from ipie.utils.backend import arraylib as xp
from ipie.utils.from_pyscf import generate_hamiltonian, generate_wavefunction_from_mo_coeff
from ipie.qmc.calc import build_afqmc_driver
from ipie.analysis.extraction import extract_observable
from ipie.estimators.estimator_base import EstimatorBase
from ipie.estimators.greens_function import greens_function
from ipie.estimators.local_energy import local_energy_G
import os
Dir = os.getcwd()+'/Mols/'
Mol = os.listdir(Dir)
print(Mol)
for i in Mol:
    molecule = Dir + i

    print(molecule)
    mol = gto.M(
        atom=molecule,
        basis="sto-3g",
        verbose=4,
        unit="Angstrom",
        
    )
    mf = scf.UHF(mol)
    mf.max_cycle=200
    mf.chkfile = "scf.chk"
    mf.kernel()
    comm = MPI.COMM_WORLD
    # Now let's build our custom AFQMC algorithm
    num_walkers = 100
    num_steps_per_block = 25
    num_blocks = 10
    timestep = 0.000005
    # 1. Build Hamiltonian
    ham = generate_hamiltonian(
        mol,
        mf.mo_coeff,
        mf.get_hcore(),
        mf.mo_coeff,  # should be optional
    )
    # 2. Build trial wavefunction
    orbs = generate_wavefunction_from_mo_coeff(
        mf.mo_coeff,
        mf.mo_occ,
        mf.mo_coeff,  # Make optional argument
        mol.nelec,
    )
    num_basis = mf.mo_coeff[0].shape[-1]
    trial = NoisySingleDet(
        np.hstack([orbs, orbs]),
        mol.nelec,
        num_basis,
        noise_level=0,
    )
    # TODO: would be nice if we didn't need to do this.
    trial.build()
    trial.half_rotate(ham)
    afqmc = AFQMC.build(
        mol.nelec,
        ham,
        trial,
        num_walkers=num_walkers,
        num_steps_per_block=num_steps_per_block,
        num_blocks=num_blocks,
        timestep=timestep,
        seed=59306159,
    )

    afqmc.run(additional_estimators=add_est)

**Expected behavior**
The expected behavior is the Hamiltonian should be built.

**Screenshots**
Output can be seen in Jupiter notebook

**Other information:**
 - Git branch and hash
 - OS: 

[e.g. macOS Monterey]
 - Version [e.g. 12.0.1]

**Additional context**
[Bug_1.zip](https://github.com/user-attachments/files/15991509/Bug_1.zip)

**Comment by fdmalone** [comment]
could you specify the molecule in a comment like so:

``` python
mol = gto.M(
    atom=molecule, # <<<< we would need this to debug
    basis="sto-3g",
    verbose=4,
    unit="Angstrom",
)
```

**Comment by Koberard** [comment]
The bug only works with specific molecules for some reason. I provided the XYZ file of the molecule in the Mols folder which is read in via 

import os
Dir = os.getcwd()+'/Mols/'
Mol = os.listdir(Dir)
print(Mol)
for i in Mol:
    molecule = Dir + i

    print(molecule)
    mol = gto.M(
        atom=molecule, ...
The contents of the XYZ file is, 
18
p-xylene[B3LYP/aug-cc-pVTZ]
C    -0.006126    0.695514    1.193928
C     0.006126   -0.695514    1.193928
C    -0.005956    0.693932   -1.191741
C     0.005956   -0.693932   -1.191741
C    -0.010665    1.417282    0.002438
C     0.010665   -1.417282    0.002438
C     0.005956    2.923660   -0.002240
C    -0.005956   -2.923660   -0.002240
H    -0.011287    1.226083    2.138293
H     0.011287   -1.226083    2.138293
H    -0.010880    1.224834   -2.136140
H     0.010880   -1.224834   -2.136140
H    -0.642816    3.326662   -0.780885
H    -0.324391    3.327444    0.954402
H     1.012311    3.306699   -0.189982
H     0.642816   -3.326662   -0.780885
H     0.324391   -3.327444    0.954402
H    -1.012311   -3.306699   -0.189982
.

**Comment by Koberard** [comment]
My software versions are the following.

OS: Ubuntu 22.04.3 LTS
python 3.11.7
Version -e git+https://github.com/linusjoonho/ipie.git@80a2444e19b846516fbf62962b7953e3a5de6137#egg=ipie

**Comment by fdmalone** [comment]
From #314 it looks like this is an issue with passing UHF mo coeffs in:

``` python
ham = generate_hamiltonian(
    mol,
    mf.mo_coeff,
    mf.get_hcore(),
    mf.mo_coeff,  # <<< should raise an error if these are UHF
```

@linusjoonho could someone look at this example and 1) confirm that it's the issue and 2) put in some assertions / raise and error if UHF integrals are found.

More generally we should try to make it as easy as possible to generate from a pyscf molecule from python, one option would be to add another factory method, or just some function which builds the objects from pyscf (trial, hamiltonian etc,) to remove some steps.

**Comment by linusjoonho** [comment]
I don't think we should raise an error. We can still take spin alpha MOs and transform them into that basis while rewriting the beta orbitals in the basis of the alpha orbitals. It needs to be done consistently with how we feed in the trial wavefunction. So, I think we should have a factory method for pyscf that takes the mf object in and produces an AFQMC driver.
We could even have AFQMC.run(mf) but I am not sure if that is going to be useful.

@jiangtong1000 what do you think?

**Comment by jiangtong1000** [comment]
I think fixing the argument of`basis_change_matrix` which also allows UHF mo_coeff is better. Will take a look

**Comment by jiangtong1000** [comment]
actually, the code already correctly identified that the UHF mo_coeff was being used as a basis_change_matrix, aligning with what Joonho suggested about using the alpha orbitals as the basis.

However, the issue originates from this specific part of the code in `chunked_cholesky` function:
https://github.com/JoonhoLee-Group/ipie/blob/bc74f33751487a034e41a31bd470fe17ccfb0cbf/ipie/utils/from_pyscf.py#L392

In the `generate_integral` function, the default tolerance (chol_cut) is set to 1e-8.
In this specific case, even after iterating to the maximum allowable nchol, the discrepancy remains at approximately 2e-8, which causes the subsequent iteration step to exceed the index range of chol_vecs, leading to the failure. This could be a bug or just some round off error I think? 

@Koberard Firstly, I will use 
```
ham = generate_hamiltonian(
        mol,
        mf.mo_coeff,
        mf.get_hcore(),
        mf.mo_coeff, 
        chol_cut=1e-6
    )
  ```
  
 This will be enough for most calculations and also can make your code runnable.

**Comment by Koberard** [comment]
Thanks for the help everyone, this should fix my issue and I'll be more carful with the orbitals I am using.
