### ISSUE TITLE
Difference between hybrid and total energy

### ISSUE THREAD

**Issue by franappi11** [JoonhoLee-Group/ipie#322]
Hi pie developers,
first thing thank you for such a powerful library! I am trying to understand the difference between total and hybrid energy. My understanding is that they should yield similar results, as seen in some previous publications(https://arxiv.org/pdf/0908.4477). The hybrid energy is used during the propagation, while the total energy, the weighted average of local energy, is computed at every block. These two quantities seems to have very different values, even for some easy case as H2. Their difference seems to be equal to mf shift in some cases, as an example for H2 with a very large distance, but not always.  I understand that a constant difference would not matter, because when  the hybrid energy is used in the importance function, this constant difference would be disappears since there is a subtraction. But it seems to me that this difference is not always constant.  Am I not considering some term ? Anything I am missing to recover some reasonable results from the local energy?  
Here I attach the output I obtained from the H6 chain of the example 1: 
<img width="838" alt="Screenshot 2024-10-08 at 16 12 02" src="https://github.com/user-attachments/assets/4f889bdd-2fa4-4b2d-a539-1504504628a5">

Thank you for any form of help!

**Comment by jiangtong1000** [comment]
Hi @franappi11 , we should avoid comparing HybridEnergy with TotalEnergy in this manner. 

In the paper you shared (Fig. 4), the y-axis consistently represents the total energy all the time. What they demonstrate is how the final total energy changes with time step  when different importance functions are employed, rather than directly comparing Hybrid Energy with Local Energy. 

(Please correct me if I didn't understand the question correctly).

**Comment by fdmalone** [comment]
The paper your referencing AFAIK is comparing the local energy approximation to the hybrid energy weight update scheme (compare Eq. 15 and Eq. 12), Eq 15 is an approximation which vanishes in the limit of small timestep. Using Eq. 15 requires you to compute the local energy (aymptotically the most expensive thing) each time step, so in practice we always use Eq 12 which only requires computing overlaps (and the force bias). In their paper they compare the local energy (the mixed estimator defined in the exponent of Eq. 14) weight update scheme with the hybrid approach but AFAIK they compute the local energy using the regular mixed estimator (not Eq. 20).

I can't quite remember what ipie does, but there are various shifts, constant factors and factors of two so you would need to be careful and I image any "growth-like" estimator would have worse statistics, they're also not exactly equivalent (timestep error) so I wouldn't expect identical results anyway.

The main reason it's printed (if I remember correctly) is it's a good signal that something bad is happening in the simulation (if it's very spiky).

**Comment by franappi11** [comment]
Okay I understand, I thought it was somehow possible to recover a correct value of the energy (even if with worse statistics) from the hybrid energy, but this seems not be the case. Thank you all for these very detailed answers!
