### ISSUE TITLE
MPI error with multi gpu runs 

### ISSUE THREAD

**Issue by zohimchandani** [JoonhoLee-Group/ipie#323]
Running [this](https://github.com/yfhuang93/ipie/tree/msd_gpu) fork of the project and having some issues with the GPU execution. 

```
afqmc_msd = AFQMC.build(
    pyscf_data["mol"].nelec,
    afqmc_hamiltonian,
    trial_wavefunction,
    num_walkers=100,
    num_steps_per_block=25,
    num_blocks=10,
    timestep=0.005,
    stabilize_freq=5,
    seed=random_seed,
    pop_control_freq=5,
    verbose=False)


afqmc_msd.run()

```

```
mpirun -np 1 --allow-run-as-root python3 test.py 
```

This executes fine but if I change to `-np 2`, I get the following error: 

```
# Start Hartree-Fock computation
# Start Hartree-Fock computation
# Start CAS computation
# Start CAS computation
# random seed is 1
# There are unused GPUs (2 MPI tasks but 8 GPUs).  Check if this is really what you wanted.
            Block                   Weight            WeightFactor            HybridEnergy                  ENumer                  EDenom                  ETotal                  E1Body                  E2Body
cupy_backends.cuda.api.runtime.CUDARuntimeError: cudaErrorInvalidValue: invalid argument
```

I guess this is expected since the code is designed to run on single GPU and multi GPU support is not available. 

However, I would like to run the script with `-np 2` since an earlier part of my code needs 2 processes. 

I can wrap the Ipie section of my code in: 

```
if rank == 0:

.....
```
However I think that the MPI communicator I am using and the one Ipie uses is conflicting. 

Is there a way to turn off the MPI in Ipie? or any other suggestions/ solutions here?

**Comment by jiangtong1000** [comment]
Not sure if I understand correctly, but sounds like you can try hacking
this part in your code.

https://github.com/JoonhoLee-Group/ipie/blob/4b60ce0c923b90e8492b35ffb0e12600d1476ff4/ipie/config.py#L27
